In [1]:
from google.cloud import bigquery

In [2]:
# Initialize the BigQuery client
client = bigquery.Client()

In [11]:
# SQL query targeting the ULB credit card fraud dataset in BQ public data
query = """
SELECT * 
FROM `bigquery-public-data.ml_datasets.ulb_fraud_detection`
"""

In [12]:
# Run the query and convert to a Pandas DataFrame
df = client.query(query).to_dataframe()

In [13]:
# Preview your data
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,282.0,-0.356466,0.725418,1.971749,0.831343,0.369681,-0.107776,0.751610,-0.120166,-0.420675,...,0.020804,0.424312,-0.015989,0.466754,-0.809962,0.657334,-0.043150,-0.046401,0.0,0
1,14332.0,1.071950,0.340678,1.784068,2.846396,-0.751538,0.403028,-0.734920,0.205807,1.092726,...,-0.169632,-0.113604,0.067643,0.468669,0.223541,-0.112355,0.014015,0.021504,0.0,0
2,32799.0,1.153477,-0.047859,1.358363,1.480620,-1.222598,-0.481690,-0.654461,0.128115,0.907095,...,0.125514,0.480049,-0.025964,0.701843,0.417245,-0.257691,0.060115,0.035332,0.0,0
3,35799.0,-0.769798,0.622325,0.242491,-0.586652,0.527819,-0.104512,0.209909,0.669861,-0.304509,...,0.152738,0.255654,-0.130237,-0.660934,-0.493374,0.331855,-0.011101,0.049089,0.0,0
4,36419.0,1.047960,0.145048,1.624573,2.932652,-0.726574,0.690451,-0.627288,0.278709,0.318434,...,0.078499,0.658942,-0.067810,0.476882,0.526830,0.219902,0.070627,0.028488,0.0,0

In [14]:
df.info

<bound method DataFrame.info of             Time        V1        V2        V3        V4        V5        V6  \
0          282.0 -0.356466  0.725418  1.971749  0.831343  0.369681 -0.107776
1        14332.0  1.071950  0.340678  1.784068  2.846396 -0.751538  0.403028
2        32799.0  1.153477 -0.047859  1.358363  1.480620 -1.222598 -0.481690
3        35799.0 -0.769798  0.622325  0.242491 -0.586652  0.527819 -0.104512
4        36419.0  1.047960  0.145048  1.624573  2.932652 -0.726574  0.690451
...          ...       ...       ...       ...       ...       ...       ...
284802  153653.0 -5.192496  3.164721 -5.047679  2.246597 -4.011781 -0.638908
284803   41138.0 -4.595617  5.083690 -7.581015  7.546033 -6.949165 -1.729185
284804   70270.0 -1.512516  1.133139 -1.601052  2.813401 -2.664503 -0.310371
284805   25095.0  1.192396  1.338974 -0.678876  3.123672  0.643245 -1.184323
284806  141565.0  0.114965  0.766762 -0.494132  0.116772  0.868169 -0.477982

              V7        V8        V9  ...       V21       V22       V23  \
0       0.751610 -0.120166 -0.420675  ...  0.020804  0.424312 -0.015989
1      -0.734920  0.205807  1.092726  ... -0.169632 -0.113604  0.067643
2      -0.654461  0.128115  0.907095  ...  0.125514  0.480049 -0.025964
3       0.209909  0.669861 -0.304509  ...  0.152738  0.255654 -0.130237
4      -0.627288  0.278709  0.318434  ...  0.078499  0.658942 -0.067810
...          ...       ...       ...  ...       ...       ...       ...
284802 -2.873463  1.576318 -2.861986  ...  1.167244 -1.006617  0.774562
284803 -8.190192  2.714670 -7.083169  ...  2.248971  0.566844  0.033744
284804 -1.520895  0.852996 -1.496495  ...  0.729828  0.485286  0.567005
284805  0.397586 -0.253499  0.411135  ... -0.377503 -0.889597 -0.074208
284806  0.438496  0.063073 -0.186207  ... -0.284413 -0.706865  0.131405

             V24       V25       V26       V27       V28  Amount  Class
0       0.466754 -0.809962  0.657334 -0.043150 -0.046401    0.00      0
1       0.468669  0.223541 -0.112355  0.014015  0.021504    0.00      0
2       0.701843  0.417245 -0.257691  0.060115  0.035332    0.00      0
3      -0.660934 -0.493374  0.331855 -0.011101  0.049089    0.00      0
4       0.476882  0.526830  0.219902  0.070627  0.028488    0.00      0
...          ...       ...       ...       ...       ...     ...    ...
284802  0.063397 -0.390658  1.884741 -1.742558 -0.082216  247.86      1
284803  0.591783  0.334229  0.386801  2.163898  0.983104  340.11      1
284804  0.323586  0.040871  0.825814  0.414482  0.267265  318.11      1
284805  0.035446  0.550578 -0.027171 -0.024921  0.073605    3.12      1
284806  0.600742 -0.604264  0.262938  0.099145  0.010810    4.49      1

[284807 rows x 31 columns]>

In [15]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.0
mean,94813.859575,1.181548e-15,3.448842e-16,-1.395504e-15,2.088465e-15,1.002719e-15,1.494498e-15,-5.556467e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.448842e-16,2.634532e-16,4.473914e-15,5.109395e-16,1.684504e-15,-3.664394e-16,-1.218471e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.0
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.0
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.0
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.0
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.0

In [16]:
df.shape

(284807, 31)

In [17]:
df.to_csv("ULB.csv")

In [18]:
import pandas as pd

In [19]:
df2 = pd.read_csv("./ulb_fraud_detection.csv")

In [20]:
df2.shape

(284807, 31)

In [21]:
df2.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,8748.0,-1.070416,0.304517,2.777064,2.154061,0.254450,-0.448529,-0.398691,0.144672,1.070900,...,-0.122032,-0.182351,0.019576,0.626023,-0.018518,-0.263291,-0.198600,0.098435,0.0,0
1,27074.0,1.165628,0.423671,0.887635,2.740163,-0.338578,-0.142846,-0.055628,-0.015325,-0.213621,...,-0.081184,-0.025694,-0.076609,0.414687,0.631032,0.077322,0.010182,0.019912,0.0,0
2,28292.0,1.050879,0.053408,1.364590,2.666158,-0.378636,1.382032,-0.766202,0.486126,0.152611,...,0.083467,0.624424,-0.157228,-0.240411,0.573061,0.244090,0.063834,0.010981,0.0,0
3,28488.0,1.070316,0.079499,1.471856,2.863786,-0.637887,0.858159,-0.687478,0.344146,0.459561,...,0.048067,0.534713,-0.098645,0.129272,0.543737,0.242724,0.065070,0.023500,0.0,0
4,31392.0,-3.680953,-4.183581,2.642743,4.263802,4.643286,-0.225053,-3.733637,1.273037,0.015661,...,0.649051,1.054124,0.795528,-0.901314,-0.425524,0.511675,0.125419,0.243671,0.0,0

In [26]:
!bq load \
  --source_format=CSV \
  --skip_leading_rows=1 \
  fraud_detection.ulb_credit_card_fraud \
  ulb_fraud_detection.csv

Upload complete.
Waiting on bqjob_r68de820034548a92_000001a00d446c16_1 ... (3s) Current status: DONE